import { Nunito, Atkinson_Hyperlegible } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import HeaderParent from "./header/headerparent";
import { Toaster } from "sonner";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  display: "swap",
});

const atkinson = Atkinson_Hyperlegible({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-atkinson",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${nunito.variable} ${atkinson.variable}`}>
      <body className=" bg-primary-800">
        <Providers>
          <Toaster
            position="bottom-right"
            toastOptions={{
              className: "!shadow-md",
              classNames: {
                title: "text-p-small",
              },
            }}
          />
          <HeaderParent />

          <main className="relative flex min-h-screen flex-col items-center justify-between   text-secondary">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
